### PR TITLE
Add CLI Arg to replace default "Me" value

### PR DESCRIPTION
**Pull request by seanwolter**
Hi! My name is Sean. I'm new to Rust and recently have a lot of free time. I want to support imessage-exporter and issue #30 seemed like a good place to start. I think these changes address the feature request.

Please feel free to shut me down, critique, or request revisions. As I said above, I'm new to Rust so this may be completely wrong.

Thanks for imessage-exporter!

### CODE REVIEW

**Comment by ReagentX** [comment]
Thank you for the contribution! At first glance this looks pretty idiomatic. I already planned the release of version 1.2 [here](https://github.com/users/ReagentX/projects/5) and I will review/merge this in once I finish working on that. 

Cheers!

**Comment by seanwolter** [comment]
I merged changes from upstream develop (and after a roundabout with VS Code's _attempts to help_) my branch is updated and conflict-free. 🫡

**Comment by ReagentX** [comment]
Hi, sorry about the conflicts. I reworked the `Options` struct in Lemonade Berry, and the validation layer has changed. It shouldn't be too pesky, you just need to remove the `valid` field from the definitions altered in this PR when you merge.

**Comment by seanwolter** [comment]
I think I merged all changes and resolved conflicts without missed anything. Should be good to go!

**Pull request merged**
