### PR TITLE
Support for Handwritten Messages

### LINKED ISSUE #31: Support Handwritten messages
Details are here: https://support.apple.com/en-us/HT206894

### PR DESCRIPTION
**Pull request by trymoose**
Fixes #31 

## HTML preview

![HTML](https://github.com/user-attachments/assets/4be83792-a3fb-415b-ad39-5c9c2e6dc0d6)

## TXT preview

```
Jul 17, 2024 9:38:09 PM (Read by you after 38 minutes, 48 seconds)
+12345678901
                                                                                                                      
                                                                      *                                               
                                                                  ****                                                
                                                               ***                                                    
                                                             **                                                       
                                                           **                                                         
                                                        ***                                                           
                                                     ***                                                              
                                                    *                                                                 
                                                  **                                                                  
                                                **                                              **                    
                                             ***                                             ***                      
                                            *                                              **                         
                                         ***                                             **                           
                                        *                                            ****                             
                                      **                                           **                                 
                                   ***                                           **                                   
                                  *                                            **                                     
                                 *                                           **                                       
                               **                                          **                                         
                              *                                          **                                         **
                            **                                         **                                           * 
                         ***                                         **                                            ** 
                        *                                         ***                                            **   
                       *                                         *                                              **    
                     **                                       ***                                              **     
                    *                                        *                                                *       
                  **                                        *                                               **        
                **                                       ***                                               *          
              **                                       **                                                **           
            **                                      ***                                                **             
           *                                     ***                                                  **              
         **                                    **                                                   **                
       **                                     *                                                    *                  
      *                                     **                                                   **                   
  ****                                   ***                                                   ***                    
 *                                    ***                                                    **                       
                                ******                                                    ***                         
                                                                                      ****                            
                                                                                                                      


Jul 17, 2024 9:38:18 PM (Read by you after 38 minutes, 39 seconds)
+12345678901
                                                                                                                                                                         
                                                                                                                                                                         
  ****************                                                                                                                                                       
                  ***************                                                                                                                                        
                                 ********************************************************************************                                                        
                                                                                                                 *****************                                       
                                                                                                                                  ************                           
                                                                                                                                              **************             
                                                                                                                                                            *************
                                                                                                                                                                         
                                                                                                                                                                         
                                                                                                                                                                         
                                                                                                                                                                         
                                                                                                                                                                         
                                                                                                                                                         **              
                                                                                                                                                          **             
                                                                                                                                                         **              
                                                                                                                                                        **               
                                                                                                                                                  ******                 
                                                                                                                                        **********                       
                                                                                                               *************************                                 
                                                                                          *********************                                                          
                                                             *****************************                                                                               
                      ***************************************                                                                                                            
                                                                                                                                                                         
                                                                                                                                                                         
                                                                                                                                                       *                 
                                                                                                                                                       *                 
                                                                                                                                                      **                 
                                                                                                                                                ******                   
                                                                                                                                      ***********                        
                                                                                                                             *********                                   
                                                                                                                      *******                                            
                                                                                                              ********                                                   
                                                                                                      ********                                                           
                                                                                               *******                                                                   
                                                                                  *************                                                                          
                                                                  ****************                                                                                       
                                                ******************                                                                                                       
                                                                                                                                                                         


Jul 17, 2024 9:38:29 PM (Read by you after 38 minutes, 28 seconds)
+12345678901
                                                                                                          
                                                                                            *             
                     *                                                                      *             
                      *                                                                     *            *
   *                  *                 *                                 *                 *            *
   *                  *                 *                                 *                 *            *
   *                  *                 *                                 *                **           **
   *                 *                 **                                *                 *            * 
   *                 *                 *                                 *                 *            * 
   *                 *                 *                                 *                 *            * 
   *                 *                *                   *              *                 *            * 
   *                 *                *                   *              *                **            * 
   *                *                 *                   *              *                *             * 
   *                *                 *                  *              *                 *             * 
  *                 *                 *                  *              *                 *             * 
  *                 *                 *                  *              *                 *            *  
  *                 *                 *                  *              *                 *            *  
  *                 *                **                  *              *                 *            *  
  *                 *                *                   *              *                 *            *  
  *                *                 *                   *              *                 *            *  
  *                *                 *                   *              *                 *            *  
  *                *                 *                   *              *                 *            *  
  *                *                 *                   *              *                *             *  
  *                *                 *                  **              *                *             *  
  *                *                **                  *               *                *             *  
  *               *                 *                   *               *                *             *  
  *               *                 *                   *               *                *             *  
  *               *                 *                   *               *                *             *  
  *               *                 *                   *               *                *             *  
 **               *                 *                   *               *                *             *  
 *               *                  *                   *               *                *             *  
 **              *                  *                   *               *                *             *  
 *               *                 *                   **               *                *             *  
                **                 *                   *               **                *             *  
                                   *                                   *                               *  
                                   *                                   *                                  
                                   *                                                                      
                                   *                                                                      
                                   *                                                                      
                                                                                                          


Jul 17, 2024 9:38:59 PM (Read by you after 37 minutes, 58 seconds)
+12345678901
                                                                                                                                                                           
          *****                                                                                                                                                            
       ***    *****                                                                                                                                                        
      **          **                                                                                                                                                       
     **             *                                                                                                                                                      
     *               *                                                                                                                                                     
    *                                                                                                                            ****                                      
   **                                                                                                                         ****  *****                                  
   *                                                               *********                                                 **         *                                  
   *                                                           ****        *****             ***********                   **            *                                 
  **                                                          **               ***         **          ***                *              *                                 
  *                                 ****                    **                   *        *              **              *              *                                  
  *                                **   **                ***                    *      **                *            **               *                                  
  *                               **     *                *                      *     *                  *           *                 *                                  
  *                              **      *               *                       *   **                  **          *                 *                                   
 **                              *       *              *                       *   **                   *          *                  *                                   
 *                               *       *              *                      **  **                   **         *                  *         *******                    
 *                              *        *             *                      **   *                    *         *                   *       ***      ***                 
 *                              *        *             *                     **   **                   **        *                   *       **          **                
 *                             *         *            **                     *    *                   **         *                  *        *            **               
 *                             *         *            *                     *     *                   *         *                  *        **             *               
 *                             *        **            *                    *      *                  *          *                  *        *              *               
 *                            **        *             *                  **       *                **           *                **         *              *               
 *                            *         *             *                  *        *                *            *                *          *              *               
 *                            *         *             *                 *         *              **             *              **           *             **               
  *                           *         *             *               **          *             **              *             **            *            **                
  *                           *        *              *              **           *           **                *            *              *           **                 
  *                           *       **              *            **             **         **                 *          **               *           *                 *
   *                          *       *               *           **               *        *                   *        **                 *         **                 **
   *                          *      *                 *       ***                  *      *                    *      ***                  *        *                 **  
   *                          **    *                  *      **                    *    **                     **   **                     **      *                 **   
    *                          **  **                   *   **                       ****                        ****                        **    **              ***     
    **                           ***                     ***                          **                         **                           *** *              ***       
     **                         *****                  ****                        *** ***                     **  **                           *****************          
      *                        **    ****          ****   ***                    **      ***                 **     **                          *                          
       **                    ***         ***********        ***                ***         ******       *****        **                       **                           
        **                 ***                                 ****************                  *******               ***                  **                             
         ****          ****                                                                                              ****            ***                               
             ***********                                                                                                     *************                                 
                                                                                                                                                                           

```

### CODE REVIEW

**Comment by ReagentX** [comment]
Will review in the coming week—would like to get this into the Prickly Pear release.

**Comment by ReagentX** [comment]
How did you generate the file at `imessage-database/src/util/handwriting/handwriting.rs`?

**Comment by trymoose** [comment]
1. Install protobuf compiler
  - `apt install -y protobuf-compiler`
  - `brew install protobuf`
2. Install rust generator: `cargo install protobuf-codegen`
3. Run `protoc --rust_out=./ ./handwriting.proto` from the `imessage-database/src/util/handwriting` directory.

**Comment by ReagentX** [comment]
Is that all you are running? I get `--rust_out: handwriting.proto: The Rust codegen is highly experimental. Future versions will break existing code. Use at your own risk. You can opt-in by passing 'experimental-codegen=enabled' to '--rust_opt'.`

On further experimentation, it seems I get the same result as this person: https://github.com/stepancheg/rust-protobuf/issues/677

**Comment by trymoose** [comment]
Odd, I get no output and the file regenerates the same. I'm on ubuntu 24.04 if that makes any difference.

**Comment by ReagentX** [comment]
I got it working using the `build.rs` method; since that is the build system I use I think that is the better way to do this anyway. I am not sure why the command you used did not work for me.

**Comment by ReagentX** [comment]
There is an overflow with very long strokes: 

[pollock.bin.zip](https://github.com/user-attachments/files/16967367/pollock.bin.zip)

https://github.com/ReagentX/imessage-exporter/blob/feat/cs/support-handwritten-messages/imessage-database/src/message_types/handwriting/models.rs/#L200-L207

If I use https://docs.rs/num/latest/num/trait.CheckedMul.html here, I get an OOB read later.

I think these handwriting integers should be `u16` and not `i16`:

```rust
fn main() {
    let a = u16::from_le_bytes([0x95, 0xad]) as usize;
    let b = i16::from_le_bytes([0x95, 0xad]) as usize;
    
    println!("{a}\n{b}");
}
```

```
44437
18446744073709530517
```

A lot of them don't make sense as signed values anyway, i.e. height, width, and count. What are your thoughts?

**Comment by trymoose** [comment]
[Looks like I got mixed up, the length of the stroke's array should be parsed as `uint16` le](https://github.com/trymoose/handwriting2svg/blob/0eb56cf458207bb1c2ceea48cf4b6b6510fa7b13/pkg/handwriting/parseStrokes.go#L21)

**Comment by trymoose** [comment]
This is what my utility generates for that input:
pollock

**Comment by ReagentX** [comment]
Yep, I made some tweaks to the Rust code that use `u16` and I get the correct result https://github.com/ReagentX/imessage-exporter/commit/a7f12f6b97e3be6773d40106b27c218088491002

**Pull request merged**
